require:
  - rubocop-capybara

inherit_gem:
  rubocop-fjord:
    - "config/rubocop.yml"
    - "config/rails.yml"

AllCops:
    SuggestExtensions: false

Rails/SkipsModelValidations:
  Exclude:
    - app/models/concerns/synchronizable.rb
    - app/models/newspaper/assigned_issue_synchronizer.rb
    - app/models/newspaper/reviewed_issue_synchronizer.rb
    - app/models/newspaper/wiki_synchronizer.rb
