require:
  - rubocop-capybara

inherit_gem:
  rubocop-fjord:
    - "config/rubocop.yml"
    - "config/rails.yml"

AllCops:
    SuggestExtensions: false

Rails/SkipsModelValidations:
  Exclude:
    - app/models/synchronizer.rb
